services:
  mariadb:
    image: mariadb:10.5
    container_name: opencart_test_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: opencart
      MYSQL_USER: opencart_user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  db_data:
